using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.GridControl.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using static Content.Shared.GridControl.Components.GridConfigComponent;
using static Content.Shared.GridControl.Components.StationTaggerComponent;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.GridControl.UI;
[GenerateTypedNameReferences]
public sealed partial class StationTaggerWindow : DefaultWindow
{
    public StationTaggerBoundUserInterface? BUI;

    public StationTaggerWindow()
    {
        RobustXamlLoader.Load(this);

        PossibleTargets.OnItemSelected += OnTargetSelected;
        LinkButton.OnPressed += OnLink;
        UnlinkButton.OnPressed += OnUnlink;
    }

    public void OnLink(ButtonEventArgs args)
    {
        if (PossibleTargets.SelectedId == 0) return;
        if (BUI != null)
        {
            BUI.SendMessage(new StationTaggerLink());
        }
    }

    public void OnUnlink(ButtonEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new StationTaggerUnlink());
        }
    }
    private void OnTargetSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new StationTaggerTargetSelect(args.Id));
        }
    }
    public void UpdateState(IPrototypeManager protoManager, StationTaggerBoundUserInterfaceState state)
    {
        PrivilegedIdLabel.Text = state.PrivilegedIdName;
        PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
            ? Loc.GetString("access-overrider-window-eject-button")
            : Loc.GetString("access-overrider-window-insert-button");

        TargetNameLabel.Text = state.TargetLabel;
        TargetNameLabel.FontColorOverride = state.TargetLabelColor;
        PossibleTargets.Clear();
        PossibleTargets.Visible = true;
        PossibleTargets.AddItem("None", 0);
        LinkButton.Pressed = false;
        if (state.PossibleStations != null)
        {
            foreach (var kv in state.PossibleStations)
            {
                PossibleTargets.AddItem(kv.Value, kv.Key);
                if (kv.Key == state.TargetStation)
                {
                    PossibleTargets.SelectId(kv.Key);
                    if (kv.Key == state.CurrentStation)
                    {
                        LinkButton.Pressed = true;
                    }
                }
            }
        }
        if (state.IsPrivilegedIdAuthorized) UnlinkButton.Disabled = false;
        else UnlinkButton.Disabled = true;
        if (state.IsPrivilegedIdAuthorized) LinkButton.Disabled = false;
        else LinkButton.Disabled = true;

        if (!LinkButton.Pressed) UnlinkButton.Pressed = true;
        else UnlinkButton.Pressed = false;
        if (state.StationName != null)
            CurrentLabel.Text = state.StationName;
        else
            CurrentLabel.Text = "*None*";
    }

}
