using System.Collections.Generic;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.CrewAssignments.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CodexEntryMenu : DefaultWindow
    {
        public CodexEntryMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        public void UpdateState(string title, string description)
        {
            this.Title = title;
            DescriptionLabel.SetMarkup(description);
        }
    }
}
