using Content.Client.CrewAssignments.AdminUI;
using Content.Shared.CrewAssignments.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;
using System.Collections.Generic;
using System.Linq;
using static Robust.Client.UserInterface.Controls.MenuBar;

namespace Content.Client.CrewAssignments.UI
{
    [GenerateTypedNameReferences]
    sealed partial class CodexEditMenu : DefaultWindow
    {
        public int _iD = 0;
        List<string> _whitelist = new List<string>();
        public CodexEui _owner;

        public void OnDeleteWhitelist(BaseButton.ButtonEventArgs args)
        {
            var i = WhitelistedNames.SelectedId;
            var s = _whitelist.ElementAtOrDefault(i);
            if (s == null) return;
            _owner.SendMessage(new CodexEuiMsg.DeleteWhitelist(_iD, s));
        }

        public void OnDelete(BaseButton.ButtonEventArgs args)
        {
            _owner.SendMessage(new CodexEuiMsg.Delete(_iD));
            Close();
        }
        public void OnSave(BaseButton.ButtonEventArgs args)
        {
            _owner.SendMessage(new CodexEuiMsg.Save(_iD, MainTitleLabel.Text, Rope.Collapse(DescriptionLabel.TextRope)));
        }
        public void OnReveal(BaseButton.ButtonEventArgs args)
        {
            _owner.SendMessage(new CodexEuiMsg.Reveal(_iD));
        }
        public void OnSaveWhitelist(BaseButton.ButtonEventArgs args)
        {
            if (WhitelistLabel.Text == "") return;
            _owner.SendMessage(new CodexEuiMsg.SaveWhitelist(_iD, WhitelistLabel.Text));
            WhitelistLabel.Text = "";

        }
        public CodexEditMenu(CodexEui owner)
        {
            _owner = owner;
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            WhitelistedNames.OnItemSelected += args => WhitelistedNames.SelectId(args.Id);
            SaveWhitelist.OnPressed += OnSaveWhitelist;
            DeleteWhitelist.OnPressed += OnDeleteWhitelist;
            Reveal.OnPressed += OnReveal;
            SaveChanges.OnPressed += OnSave;
            DeleteButton.OnPressed += OnDelete;
        }
        public void UpdateState(int iD, string title, string description, List<string> whitelist, bool visible)
        {
            _iD = iD;
            _whitelist = whitelist;
            MainTitleLabel.Text = title;
            DescriptionLabel.TextRope = new Rope.Leaf(description);
            WhitelistedNames.Clear();
            foreach (string name in whitelist)
            {
                WhitelistedNames.AddItem(name);
            }
            if(visible)
            {
                Reveal.Text = "Hide for Everyone";
            }
            else
            {
                Reveal.Text = "Reveal for Everyone";
            }

        }
    }
}
