using Content.Client.Actions;
using Content.Client.Cargo.UI;
using Content.Client.Message;
using Content.Shared.CrewAssignments;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using System.Text;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class JobNetMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public TimeSpan UntilNextPay = TimeSpan.Zero;
    public event Action<ButtonEventArgs>? OnJobPressed;
    public JobNetMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MasterTabContainer.SetTabTitle(0, "Job Network");
        MasterTabContainer.SetTabTitle(1, "Historic Achievements");
        MasterTabContainer.SetTabTitle(2, "Threshold Codex");
    }
     
    public void UpdateState(JobNetUpdateState state)
    {
        PossibleJobs.Clear();
        PossibleJobs.AddItem("Off Duty", 0);
        if(state.Stations != null)
        {
            int ind = 1;
            foreach (var kv in state.Stations)
            {

                PossibleJobs.AddItem(kv.Value, kv.Key);
                if(kv.Key == state.SelectedStation)
                    PossibleJobs.Select(ind);
                ind++;
            }
        }
        if (state.AssignmentName != null)
        {
            CSLabel.Text = state.AssignmentName;
            AssignmentDetails.Visible = true;
        }
        else
        {
            CSLabel.Text = "Off Duty";
            AssignmentDetails.Visible = false;
        }
        if (state.Wage != null)
        {
            WageLabel.Text = "$" + state.Wage.ToString();
        }
        else
        {
            WageLabel.Text = "$0";
        }
        if(state.RemainingMinutes != null)
        {
            UntilNextPay = state.RemainingMinutes.Value;
            TimeLabel.Text = UntilNextPay.ToString("mm\\:ss");
        }
        else
        {
            TimeLabel.Text = "Invalid";
        }
        CurrentObjectives.RemoveAllChildren();
        foreach (var objective in state.CurrentObjectives)
        {
            if (!objective.Visible) continue;
            WorldObjectiveEntryFragment entry = new(objective.Title,objective.Description,objective.Reward,null,null);
            CurrentObjectives.AddChild(entry);
        }
        CompletedObjectives.RemoveAllChildren();
        foreach (var objective in state.CompletedObjectives)
        {
            if (!objective.Visible) continue;
            WorldObjectiveEntryFragment entry = new(objective.Title, objective.Description, objective.Reward, objective.CompletedTime, objective.CompletedDescription);
            CompletedObjectives.AddChild(entry);
        }
    }

    private void UpdateSkipButton(float deltaSeconds)
    {
        UntilNextPay -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextPay > TimeSpan.Zero)
        {
            TimeLabel.Text = UntilNextPay.ToString("mm\\:ss");
            return;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
    }

}
public sealed class JobButton : Button
{
    public int Id;
}
