using Content.Client.CrewAssignments.UI;
using Content.Shared.CrewAssignments.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;

namespace Content.Client.CrewAssignments.AdminUI;

[GenerateTypedNameReferences]
public sealed partial class AdminWorldObjectivesWindow : DefaultWindow
{


    public AdminWorldObjectivesEui _owner;

    [Dependency] private readonly IResourceCache _resCache = default!;

    public AdminWorldObjectivesWindow(AdminWorldObjectivesEui owner)
    {
        _owner = owner;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var loc = IoCManager.Resolve<ILocalizationManager>();
        CreateButton.OnPressed += CreateMessage;
    }

    public void PopulateWorldObjectives(List<WorldObjectivesEntry> currentObjectives, List<WorldObjectivesEntry> completedObjectives)
    {
        CurrentObjectives.RemoveAllChildren();
        foreach (var objective in currentObjectives)
        {
            WorldObjectiveEdit worldEdit = new(objective.ID, objective.Title, objective.Description, objective.Reward, objective.CompletedTime, objective.CompletedDescription);
            if(objective.Visible)
            {
                Button completeButton = new();
                completeButton.Text = "Complete";
                completeButton.OnPressed += _ => OnComplete(objective.ID, worldEdit);
                worldEdit.MainContainer.AddChild(completeButton);
            }
            else
            {
                Button revealButton = new();
                revealButton.Text = "Reveal";
                revealButton.OnPressed += _ => OnReveal(objective.ID, worldEdit);
                worldEdit.MainContainer.AddChild(revealButton);
            }
            Button saveButton = new();
            saveButton.Text = "Save Changes";
            saveButton.OnPressed += _ => OnSaveCurrent(objective.ID, worldEdit);
            worldEdit.MainContainer.AddChild(saveButton);
            Button deleteButton = new();
            deleteButton.Text = "Delete";
            deleteButton.OnPressed += _ => OnDeleteCurrent(objective.ID);
            worldEdit.MainContainer.AddChild(deleteButton);
            CurrentObjectives.AddChild(worldEdit);
        }
        CompletedObjectives.RemoveAllChildren();
        foreach (var objective in completedObjectives)
        {
            WorldObjectiveEdit worldEdit = new(objective.ID, objective.Title, objective.Description, objective.Reward, objective.CompletedTime, objective.CompletedDescription);
            Button saveButton = new();
            saveButton.Text = "Save Changes";
            saveButton.OnPressed += _ => OnSaveCompleted(objective.ID, worldEdit);
            worldEdit.MainContainer.AddChild(saveButton);
            Button deleteButton = new();
            deleteButton.Text = "Delete";
            deleteButton.OnPressed += _ => OnDeleteCompleted(objective.ID);
            worldEdit.MainContainer.AddChild(deleteButton);
            CompletedObjectives.AddChild(worldEdit);
        }
    }

    private void CreateMessage(BaseButton.ButtonEventArgs obj)
    {
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.CreateNew());
    }
    private void OnComplete(int id, WorldObjectiveEdit edit)
    {
        OnSaveCurrent(id, edit);
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.Complete(id));
    }
    private void OnReveal(int id, WorldObjectiveEdit edit)
    {
        OnSaveCurrent(id, edit);
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.Reveal(id));
    }
    private void OnDeleteCurrent(int id)
    {
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.Delete(id));
    }
    private void OnDeleteCompleted(int id)
    {
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.DeleteCompleted(id));
    }

    private void OnSaveCurrent(int id, WorldObjectiveEdit edit)
    {
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.SaveChanges(id, edit.TitleLabel.Text, Rope.Collapse(edit.DescriptionLabel.TextRope), Rope.Collapse(edit.RewardLabel.TextRope), Rope.Collapse(edit.CompletedDescriptionLabel.TextRope)));
    }

    private void OnSaveCompleted(int id, WorldObjectiveEdit edit)
    {
        _owner.SendMessage(new AdminWorldObjectivesEuiMsg.SaveChangesCompleted(id, edit.TitleLabel.Text, Rope.Collapse(edit.DescriptionLabel.TextRope), Rope.Collapse(edit.RewardLabel.TextRope), Rope.Collapse(edit.CompletedDescriptionLabel.TextRope)));
    }
}
