using Content.Client.CrewAssignments.UI;
using Content.Shared.CrewAssignments.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;

namespace Content.Client.CrewAssignments.AdminUI;

[GenerateTypedNameReferences]
public sealed partial class CodexWindow : DefaultWindow
{

    public CodexEui _owner;

    [Dependency] private readonly IResourceCache _resCache = default!;

    public CodexWindow(CodexEui owner)
    {
        _owner = owner;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var loc = IoCManager.Resolve<ILocalizationManager>();
    }
}
