using Content.Client.Actions;
using Content.Client.Cargo.UI;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared.AcceptDeath;
using Content.Shared.CrewAssignments;
using Content.Shared.CrewAssignments.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.Timing;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using System.Text;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.MenuBar;

namespace Content.Client.AcceptDeath;

[GenerateTypedNameReferences]
public sealed partial class AcceptDeathMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public TimeSpan ACDCooldown = TimeSpan.Zero;
    public TimeSpan SOSCooldown = TimeSpan.Zero;
    public event Action<ButtonEventArgs>? OnJobPressed;

    public AcceptDeathBoundUserInterface? _owner;

    public AcceptDeathMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
    }
     
    public void UpdateState(AcceptDeathUpdateState state)
    {
        ACDCooldown = state.acceptDeathCooldown;
        SOSCooldown = state.sosCooldown;
        if(ACDCooldown > TimeSpan.Zero)
        {
            AcceptDeathButton.Disabled = true;
            AcceptDeathButton.Text = $"Available in:{ACDCooldown.ToString("mm\\:ss")}";
        }
        else
        {
            AcceptDeathButton.Disabled = false;
            AcceptDeathButton.Text = $"Accept Death";
        }
        if(SOSCooldown > TimeSpan.Zero)
        {
            SOSButton.Disabled = true;
            SOSButton.Text = $"Available in:{SOSCooldown.ToString("mm\\:ss")}";
        }
        else
        {
            SOSButton.Disabled = false;
            SOSButton.Text = "Broadcast SOS";
        }
    }
    private void UpdateSkipButton(float deltaSeconds)
    {
        ACDCooldown -= TimeSpan.FromSeconds(deltaSeconds);
        if (ACDCooldown > TimeSpan.Zero)
        {
            AcceptDeathButton.Disabled = true;
            AcceptDeathButton.Text = $"Available in:{ACDCooldown.ToString("mm\\:ss")}";
        }
        else
        {
            AcceptDeathButton.Disabled = false;
            AcceptDeathButton.Text = $"Accept Death";
        }
        SOSCooldown -= TimeSpan.FromSeconds(deltaSeconds);
        if (SOSCooldown > TimeSpan.Zero)
        {
            SOSButton.Disabled = true;
            SOSButton.Text = $"Available in:{SOSCooldown.ToString("mm\\:ss")}";
        }
        else
        {
            SOSButton.Disabled = false;
            SOSButton.Text = "Broadcast SOS";
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
    }

}
