- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData
    - type: CrewAssignments
    - type: CrewRecords
    - type: CrewAccesses


- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
      orders:
        Cargo: [ ]
        Engineering: [ ]
        Medical: [ ]
        Science: [ ]
        Security: [ ]
        Service: [ ]
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSalvageJobs
  abstract: true
  components:
  - type: SalvageJobsData
    rankThresholds:
      0:
        title: salvage-job-rank-title-0
        bountyGroup: SalvageJobTier1
      3:
        title: salvage-job-rank-title-1
        bountyGroup: SalvageJobTier2
        unlockedMarket: SalvageJobReward2
      6:
        title: salvage-job-rank-title-2
        bountyGroup: SalvageJobTier3
        unlockedMarket: SalvageJobReward3
    maxRank:
      title: salvage-job-rank-title-MAX
      unlockedMarket: SalvageJobRewardMAX

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationDeliveries
  abstract: true
  components:
  - type: CargoDeliveryData

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
