using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoBountyMenu : FancyWindow
{
    public Action<string>? OnLabelButtonPressed;
    public Action<string>? OnSkipButtonPressed;
    public TimeSpan UntilNextSkip = TimeSpan.Zero;

    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    public CargoBountyMenu()
    {
        RobustXamlLoader.Load(this);

        MasterTabContainer.SetTabTitle(0, Loc.GetString("bounty-console-tab-history-label"));
    }

    public void UpdateEntries(Dictionary<ProtoId<CargoBountyGroupPrototype>, List<CargoBountyData>> bounties, List<CargoBountyHistoryData> history, TimeSpan untilNextSkip, CargoBountyConsoleState state)
    {
        PossibleTrades.Clear();
        PossibleTrades.AddItem("None", 0);
        foreach (var kv in state.PossibleTrades)
        {

            PossibleTrades.AddItem(kv.Value, kv.Key);
            if (kv.Key == state.SelectedTrade)
            {
                PossibleTrades.SelectId(kv.Key);
            }
        }
        ResetText.Text = untilNextSkip.ToString("hh\\:mm\\:ss");
        UntilNextSkip = untilNextSkip;
        var historyTab = MasterTabContainer.GetChild(0);
        MasterTabContainer.RemoveAllChildren();
        if(historyTab != null) MasterTabContainer.AddChild(historyTab);
        foreach (var kv in bounties)
        {
            _protoManager.Resolve(kv.Key, out var groupProto);
            if (groupProto == null) continue;
            ScrollContainer sc = new();
            sc.HScrollEnabled = false;
            sc.VerticalExpand = true;
            sc.HorizontalExpand = true;
            BoxContainer bc = new();
            bc.Orientation = BoxContainer.LayoutOrientation.Vertical;
            bc.VerticalExpand = true;
            bc.HorizontalExpand = true;
            sc.AddChild(bc);
            MasterTabContainer.AddChild(sc);
            MasterTabContainer.SetTabTitle(MasterTabContainer.ChildCount - 1, groupProto.Name);
            foreach (var b in kv.Value)
            {
                var entry = new BountyEntry(b, untilNextSkip);
                entry.OnLabelButtonPressed += () => OnLabelButtonPressed?.Invoke(b.Id);
                bc.AddChild(entry);
            }
        }
        BountyHistoryContainer.Children.Clear();
        if (history.Count == 0)
        {
            NoHistoryLabel.Visible = true;
        }
        else
        {
            NoHistoryLabel.Visible = false;

            // Show the history in reverse, so last entry is first in the list
            for (var i = history.Count - 1; i >= 0; i--)
            {
                BountyHistoryContainer.AddChild(new BountyHistoryEntry(history[i]));
            }
        }
        TaxText.Text = $"{state.TaxRate}%";
        LevelText.Text = state.ILevelTitle;
        LevelBar.MaxValue = state.PromotionExp;
        LevelBar.MinValue = state.DemotionExp;
        LevelBar.Value = state.Exp;
        LevelBarText.Text = $"{state.Exp}/{state.PromotionExp}";
        FactionText.Text = state.Owner;
        TradeStationDetails.Visible = true;
        if (state.SelectedTrade == null || state.SelectedTrade == 0)
        {
            TradeStationDetails.Visible = false;
        }
    }


    private void UpdateSkipButton(float deltaSeconds)
    {
        UntilNextSkip -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextSkip > TimeSpan.Zero)
        {
            ResetText.Text = UntilNextSkip.ToString("hh\\:mm\\:ss");
            return;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
    }
}
