using Content.Client.Radio.Ui;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.GridControl.Components;
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Radio.Ui;
[GenerateTypedNameReferences]
public sealed partial class HeadsetMenuWindow : DefaultWindow
{
    public HeadsetMenuBoundUserInterface? BUI;

    public HeadsetMenuWindow()
    {
        RobustXamlLoader.Load(this);
        PossibleInputs.OnItemSelected += OnInputSelected;
        PossibleOutputs.OnItemSelected += OnOutputSelected;
    }

    private void OnInputSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new HeadsetMenuInputSelect(args.Id));
        }
    }
    private void OnOutputSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new HeadsetMenuOutputSelect(args.Id));
        }
    }
    public void UpdateState(IPrototypeManager protoManager, HeadsetMenuBoundUserInterfaceState state)
    {
        PossibleInputs.Clear();
        PossibleOutputs.Clear();
        PossibleInputs.AddItem("All");
        PossibleOutputs.AddItem("All");
        foreach (var kv in state.FormattedStations)
        {
            PossibleInputs.AddItem(kv.Value, kv.Key);
            PossibleOutputs.AddItem(kv.Value, kv.Key);
        }
        if (state.RecieveFrom != 0 && !PossibleInputs.TrySelectId(state.RecieveFrom))
        {
            if (BUI != null)
            {
                BUI.SendMessage(new HeadsetMenuInputSelect(0));
            }
        }
        if(state.TransmitTo != 0 && !PossibleOutputs.TrySelectId(state.TransmitTo))
        {
            if (BUI != null)
            {
                BUI.SendMessage(new HeadsetMenuOutputSelect(0));
            }
        }


    }

}
